### ISSUE TITLE
Include parenthesis point is on as part of current sexp

### ISSUE THREAD

**Issue by tuhdo** [tsdh/highlight-parentheses.el#13]
Currently, when point is on a parenthesis, the highlighting moves up a level. I think it would be more consistent if we treat parens as part of current sexp, instead of upper scope.

**Comment by tsdh** [comment]
I tend to disagree.  The mode description says it highlights the surrounding parentheses which means to me the parentheses surrounding the sexp at point.  If that sexp is a list because point is either on the opening or closing paren, I think it makes sense to move highlighting up/down in that case.

Aside from that, the current behavior is also better implementation-wise because it matches the behavior of `syntax-ppss` and `scan-sexps`.

**Comment by tuhdo** [comment]
Maybe there should be an option? Currently I have to use `show-paren-mode` to show the matching paren at point. I would love only using `highlight-parentheses` to show me matching paren and current scope.

**Comment by tsdh** [comment]
I also use `show-paren-mode` with a much more obtrusive face.

Anyhow, I'd accept a patch which adds an option to enable the behavior prefered by you.

**Comment by tsdh** [comment]
Realized by pending PR #20.
