### ISSUE TITLE
Javascript ES6 template literals

### ISSUE THREAD

**Issue by MPE2016** [tsdh/highlight-parentheses.el#23]
L.S.,

I like highlight-parentheses a lot. Makes life better. There is one use case, however, where I would like to see it implemented: Javascript ES6 template literals. 

As far as I can tell, right now, everything between back ticks is excluded from highlight parentheses, which means no highlighting of parentheses in template literals in Javascript. 

Is there a way to get around this?

All the best,

MPE

**Comment by tsdh** [comment]
Well, highlighting is not done in strings (because it is totally ok if there are unbalanced parens in a string).  It seems likely that  JavaScript mode you are using gives backticks the same syntax class as double-quotes have so to emacs (and highlight-parentheses) such a ES6 template literal looks like a string.

When you set point on a backtick and do `M-x describe-char`, what is printed as syntax class?  If it is something like `syntax: " 	which means: string` (or some other kind of string class), then that's the reason.

**Comment by tsdh** [comment]
Ok, now I've googled what template literals actually are, and in fact they **are** strings, possibly with embedded expressions.  So for example

```javascript
function foo() {
    return `Examples:
  a) 1 + 2 = ${1 + 3}
  b) 2 + 3 = ${2 + 3}`
}
```
is a perfectly fine function returning a template literal.  But template literal's parens are obviously unbalanced (which is totally okay for a string).  If highlight-parentheses would account for them, it would cause mismatches because parens/braces/brackets starting outside a string could be ended by parens/braces/brackets inside a string.

So I'll close the report.  But thanks a lot for the compliments! :+1: :tada:

**Comment by MPE2016** [comment]
Hi Tassilo,

Thanks for the explanation, completely clear.

All the best,

Maarten Pelgrim

Op donderdag 3 december 2020 om 13u42 schreef Tassilo Horn 
<notifications@github.com>:

**Comment by MPE2016** [comment]
And of course I shouldn't have assumed that you knew what javascript 
template literals are, so apologies for that:).

Op vrijdag 4 december 2020 om 10u32 schreef Maarten Pelgrim 
<maartenpelgrim@runbox.com>:
